### ISSUE TITLE
No Sound?

### ISSUE THREAD

**Issue by NeonMarie** [Ccode-lang/LethalSirenHead#9] opened 2024-03-15 01:32 UTC
I noticed Siren Head doesn't make any radio sounds when he spawns except for the person hosting. All the other players only hear his stomping. Any idea what could be causing this?

**Comment by Ccode-lang** [comment] 2024-03-16 00:22
I tested to see if this worked before release. What version are you on?

I've seen reviews of it working also.

**Comment by Ccode-lang** [comment] 2024-03-16 03:18
This might also be caused by the clients being behind a version

**Comment by NeonMarie** [comment] 2024-03-16 03:56
Says I'm on v1.2.1

**Comment by SAM0AS** [comment] 2024-03-16 05:42
Same issue here. Brother and I tested it. We switched between who was hosting. Only the host can hear the alert sounds. Everyone can hear the footsteps. Everything is up to date and we tested without other mods to rule out conflicts.

**Comment by Ccode-lang** [comment] 2024-03-21 05:47
I tested and can reproduce the spot sounds not working but the walkie seems to work.

**Comment by Ccode-lang** [comment] 2024-03-24 16:15
Fixed with the newest update. I'm pushing it right now.

**Closed as completed by Ccode-lang** 2024-03-24 16:15 UTC
